### ISSUE TITLE
Gazetteer Constructuon Details

### ISSUE THREAD

**Issue by appledora** [Mckysse/USTC-NELSLIP-SemEval2022Task11-IGNF#1]
Hello! first of all, really appreciate your interesting work and project on the NER task. I too am working on a NER for the Bengali language and your work provides a really interesting insight. The paper was a very good read. However, I was wondering whether it would be possible to get some more info on the Gazetteer construction process - particularly a codebase or similar repos, how the mapping was performed programmatically and the types of manual adjustments of mapping relationships you have had to perform.
Thanks.

**Comment by Mckysse** [comment]
We have replied to you in the email. Please kindly check.

**Comment by appledora** [comment]
Thanks, received!
