### ISSUE TITLE
 list index out of range

### ISSUE THREAD

**Issue by scholar-wu** [Mckysse/USTC-NELSLIP-SemEval2022Task11-IGNF#2]
你好，我在运行训练代码时，遇到了这样的问题。能解答一下吗？感谢！！
![image](https://user-images.githubusercontent.com/109719507/204521811-fe8eeae1-9107-4759-8043-fbac5e03032f.png)

**Comment by Mckysse** [comment]
看错误我觉得可能你是在数据处理的时候出现的问题，比方说未考虑到数据开头的空行或者末尾的额外空行？你可以针对一份样例数据对着每一步看一下处理输出的情况是否符合预期。
